/**
 * Tatlı krizi için hafif tatlı tarifleri.
 * Besin değerleri, malzeme gramajlarından USDA FoodData Central (SR Legacy / Foundation)
 * 100 g değerleri ile porsiyon başına hesaplanmıştır. Karbonhidrat toplam karbonhidrattır (lif dahil).
 * Ölçüler: su bardağı = 200 ml, çay bardağı = 100 ml.
 */
export interface SweetRecipe {
  id: string
  name: string
  minutes: number
  servings: number
  ingredients: { name: string; grams: number; measure?: string }[]
  steps: string[]
  perServing: { kcal: number; protein: number; carb: number; fat: number }
  tags: ('dairy' | 'egg' | 'gluten' | 'nuts')[]
  vegan: boolean
  /** ≤ 10 g karbonhidrat / porsiyon */
  lowCarb: boolean
  /** Pişirme gerektirmez */
  noCook: boolean
  why: string
}

export const SWEET_RECIPES: SweetRecipe[] = [
  {
    id: 'az-sekerli-kabak-tatlisi',
    name: 'Az şekerli kabak tatlısı (cevizli)',
    minutes: 70,
    servings: 4,
    ingredients: [
      { name: 'bal kabağı', grams: 600, measure: '4 dilim' },
      { name: 'toz şeker', grams: 40, measure: '3 yemek kaşığı' },
      { name: 'karanfil', grams: 0, measure: '3–4 tane' },
      { name: 'ceviz içi', grams: 24, measure: '2,5 yemek kaşığı (dövülmüş)' },
      { name: 'tarçın', grams: 1, measure: '1 çay kaşığı' },
    ],
    steps: [
      'Kabakları kabuğundan ayırıp iri dilimler halinde tencereye dizin.',
      'Üzerine şekeri serpin, karanfilleri ekleyin; suyunu salması için en az 2 saat (ya da bir gece) bekletin.',
      'Kapağı kapalı, kısık ateşte kendi suyuyla 40–45 dakika yumuşayana kadar pişirin.',
      'Soğuyunca tarçın ve dövülmüş cevizle servis edin.',
    ],
    perServing: { kcal: 118, protein: 2.4, carb: 20.8, fat: 4.1 },
    tags: ['nuts'],
    vegan: true,
    lowCarb: false,
    noCook: false,
    why: 'Klasik tarifin yaklaşık üçte biri kadar şekerle yapılır; ceviz tokluk veren yağ ve biraz protein ekler.',
  },
  {
    id: 'light-sutlac',
    name: 'Light sütlaç',
    minutes: 45,
    servings: 5,
    ingredients: [
      { name: 'yağsız süt', grams: 800, measure: '4 su bardağı' },
      { name: 'pirinç', grams: 50, measure: '1/4 su bardağı' },
      { name: 'su', grams: 150, measure: '3/4 su bardağı' },
      { name: 'mısır nişastası', grams: 15, measure: '1 yemek kaşığı' },
      { name: 'toz şeker', grams: 40, measure: '3 yemek kaşığı' },
      { name: 'tarçın', grams: 1, measure: 'üzeri için' },
    ],
    steps: [
      'Yıkanmış pirinci suyla, suyunu çekene kadar haşlayın.',
      'Sütü ekleyip kısık ateşte ara ara karıştırarak 20 dakika pişirin.',
      'Nişastayı yarım çay bardağı soğuk sütte açıp şekerle birlikte tencereye ekleyin.',
      '5 dakika daha koyulaşana kadar karıştırın, kaselere paylaştırıp soğutun; tarçınla servis edin.',
    ],
    perServing: { kcal: 134, protein: 6.2, carb: 26.9, fat: 0.2 },
    tags: ['dairy'],
    vegan: false,
    lowCarb: false,
    noCook: false,
    why: 'Yağsız süt ve azaltılmış şekerle porsiyon başı kalori düşer, sütten protein ve kalsiyum gelir.',
  },
  {
    id: 'light-muhallebi',
    name: 'Light vanilyalı muhallebi',
    minutes: 20,
    servings: 4,
    ingredients: [
      { name: 'yağsız süt', grams: 500, measure: '2,5 su bardağı' },
      { name: 'mısır nişastası', grams: 35, measure: '3 yemek kaşığı' },
      { name: 'toz şeker', grams: 25, measure: '2 yemek kaşığı' },
      { name: 'vanilin', grams: 0, measure: '1 paket' },
      { name: 'tarçın', grams: 1, measure: 'üzeri için' },
    ],
    steps: [
      'Soğuk süt, nişasta ve şekeri tencerede pürüzsüz olana kadar çırpın.',
      'Orta ateşte sürekli karıştırarak kaynayıp koyulaşana kadar pişirin.',
      'Ocaktan alıp vanilini ekleyin, kaselere paylaştırın.',
      'Buzdolabında en az 1 saat soğutup tarçınla servis edin.',
    ],
    perServing: { kcal: 101, protein: 4.3, carb: 20.7, fat: 0.1 },
    tags: ['dairy'],
    vegan: false,
    lowCarb: false,
    noCook: false,
    why: 'Küçük kaselerde porsiyonlanmış, az şekerli bir sütlü tatlı; kontrollü porsiyon ile tatlı ihtiyacını karşılar.',
  },
  {
    id: 'firin-ayva',
    name: 'Fırın ayva (süzme yoğurtlu)',
    minutes: 60,
    servings: 4,
    ingredients: [
      { name: 'ayva', grams: 400, measure: '2 orta boy' },
      { name: 'üzüm pekmezi', grams: 20, measure: '1 yemek kaşığı' },
      { name: 'karanfil', grams: 0, measure: '6–8 tane' },
      { name: 'su', grams: 200, measure: '1 su bardağı' },
      { name: 'yağsız süzme yoğurt', grams: 100, measure: '4 yemek kaşığı' },
      { name: 'ceviz içi', grams: 20, measure: '2 yemek kaşığı' },
    ],
    steps: [
      'Ayvaları kabuklarıyla ikiye kesip çekirdek yuvalarını oyun, yuvalara karanfil batırın.',
      'Fırın kabına dizip suyu ekleyin, üzerlerine pekmezi gezdirin.',
      'Üstü folyo ile kapalı olarak 180 °C fırında 40–45 dakika yumuşayana kadar pişirin.',
      'Ilınınca her yarımı bir yemek kaşığı süzme yoğurt ve dövülmüş cevizle servis edin.',
    ],
    perServing: { kcal: 119, protein: 3.7, carb: 20.6, fat: 3.5 },
    tags: ['dairy', 'nuts'],
    vegan: false,
    lowCarb: false,
    noCook: false,
    why: 'Ayva lif açısından zengin; kaymak yerine süzme yoğurt kalori yerine protein ekler.',
  },
  {
    id: 'keciboynuzlu-sicak-sut',
    name: 'Keçiboynuzlu sıcak süt',
    minutes: 5,
    servings: 1,
    ingredients: [
      { name: 'yağsız süt', grams: 200, measure: '1 su bardağı' },
      { name: 'keçiboynuzu tozu', grams: 3, measure: '1 tatlı kaşığı' },
      { name: 'keçiboynuzu pekmezi', grams: 8, measure: '1 tatlı kaşığı' },
      { name: 'tarçın', grams: 1, measure: '1 tutam' },
    ],
    steps: [
      'Sütü küçük bir cezvede ısıtın.',
      'Keçiboynuzu tozunu ekleyip topaklanmaması için çırpın.',
      'Ocaktan alınca pekmez ve tarçını karıştırıp sıcak için.',
    ],
    perServing: { kcal: 100, protein: 7.0, carb: 19.4, fat: 0.2 },
    tags: ['dairy'],
    vegan: false,
    lowCarb: false,
    noCook: false,
    why: 'Keçiboynuzu doğal tatlılık ve lif verir; sıcak süt akşam tatlı isteğini düşük kaloriyle bastırır.',
  },
  {
    id: 'tahin-pekmezli-yogurt',
    name: 'Tahin-pekmezli süzme yoğurt',
    minutes: 3,
    servings: 1,
    ingredients: [
      { name: 'yağsız süzme yoğurt', grams: 100, measure: '4 yemek kaşığı' },
      { name: 'tahin', grams: 8, measure: '1 tatlı kaşığı' },
      { name: 'üzüm pekmezi', grams: 10, measure: '1 tatlı kaşığı' },
    ],
    steps: [
      'Süzme yoğurdu küçük bir kaseye alın.',
      'Tahin ve pekmezi üzerine gezdirin.',
      'Karıştırmadan, kaşık kaşık yiyin.',
    ],
    perServing: { kcal: 136, protein: 11.6, carb: 12.8, fat: 4.7 },
    tags: ['dairy'],
    vegan: false,
    lowCarb: false,
    noCook: true,
    why: 'Tahin-pekmez tadını küçük porsiyonda verir; süzme yoğurt 10 g protein ekleyerek tokluğu uzatır.',
  },
  {
    id: 'cevizli-kuru-incir',
    name: 'Cevizli kuru incir',
    minutes: 2,
    servings: 1,
    ingredients: [
      { name: 'kuru incir', grams: 40, measure: '2 adet' },
      { name: 'ceviz içi', grams: 8, measure: '2 yarım ceviz içi' },
    ],
    steps: [
      'Kuru incirlerin sapını kesip ortadan hafifçe yarın.',
      'Her birinin içine bir yarım ceviz yerleştirin.',
      'Yavaşça, çay ya da kahve eşliğinde yiyin.',
    ],
    perServing: { kcal: 152, protein: 2.5, carb: 26.7, fat: 5.6 },
    tags: ['nuts'],
    vegan: true,
    lowCarb: false,
    noCook: true,
    why: 'İncir lif, ceviz sağlıklı yağ verir; iki adetle sınırlı porsiyon tatlı krizini hızlıca keser.',
  },
  {
    id: 'light-irmik-tatlisi',
    name: 'Light sütlü irmik tatlısı',
    minutes: 20,
    servings: 4,
    ingredients: [
      { name: 'yağsız süt', grams: 600, measure: '3 su bardağı' },
      { name: 'irmik', grams: 60, measure: '5 yemek kaşığı' },
      { name: 'toz şeker', grams: 30, measure: '2,5 yemek kaşığı' },
      { name: 'vanilin', grams: 0, measure: '1 paket' },
      { name: 'tarçın', grams: 1, measure: 'üzeri için' },
    ],
    steps: [
      'Sütü ve şekeri tencerede ılıtın.',
      'İrmiği yavaş yavaş ekleyip sürekli karıştırarak kısık ateşte koyulaşana kadar pişirin (8–10 dakika).',
      'Vanilini ekleyip ıslatılmış küçük kaselere ya da kalıplara paylaştırın.',
      'Soğuyunca ters çevirip tarçınla servis edin.',
    ],
    perServing: { kcal: 135, protein: 7.0, carb: 26.1, fat: 0.3 },
    tags: ['dairy', 'gluten'],
    vegan: false,
    lowCarb: false,
    noCook: false,
    why: 'Tereyağında kavrulan klasik irmik helvasına göre çok daha az yağ ve şekerle, sütten protein içerir.',
  },
  {
    id: 'kakaolu-suzme-yogurt-puding',
    name: 'Kakaolu süzme yoğurt pudingi',
    minutes: 3,
    servings: 1,
    ingredients: [
      { name: 'yağsız süzme yoğurt', grams: 150, measure: '6 yemek kaşığı' },
      { name: 'şekersiz kakao', grams: 4, measure: '2 tatlı kaşığı' },
      { name: 'vanilin', grams: 0, measure: '1 tutam' },
      { name: 'tatlandırıcı (isteğe bağlı)', grams: 0 },
    ],
    steps: [
      'Süzme yoğurdu kaseye alın.',
      'Kakao, vanilin ve isteğe bağlı tatlandırıcıyı ekleyin.',
      'Puding kıvamına gelene kadar iyice çırpın; 10 dakika buzdolabında bekletirseniz koyulaşır.',
    ],
    perServing: { kcal: 98, protein: 16.1, carb: 7.7, fat: 1.1 },
    tags: ['dairy'],
    vegan: false,
    lowCarb: true,
    noCook: true,
    why: 'Yaklaşık 16 g protein ile çikolatalı puding tadı; yüksek protein uzun süre tok tutar.',
  },
  {
    id: 'lorlu-cheesecake-kase',
    name: 'Lorlu cheesecake kase',
    minutes: 7,
    servings: 1,
    ingredients: [
      { name: 'lor peyniri', grams: 100, measure: '4 yemek kaşığı' },
      { name: 'yağsız süzme yoğurt', grams: 50, measure: '2 yemek kaşığı' },
      { name: 'limon kabuğu rendesi', grams: 0, measure: '1 çay kaşığı' },
      { name: 'bal', grams: 8, measure: '1 tatlı kaşığı' },
      { name: 'yulaf ezmesi', grams: 15, measure: '2 yemek kaşığı' },
      { name: 'tarçın', grams: 1, measure: '1 tutam' },
      { name: 'çilek', grams: 50, measure: '3–4 adet' },
    ],
    steps: [
      'Lor, süzme yoğurt, limon kabuğu ve balı blenderda ya da çatalla pürüzsüz olana kadar ezin.',
      'Yulaf ezmesini tarçınla karıştırıp kasenin dibine serin.',
      'Üzerine lor kremasını yayın.',
      'Doğranmış çileklerle kaplayıp hemen ya da soğutarak servis edin.',
    ],
    perServing: { kcal: 201, protein: 19.9, carb: 25.9, fat: 2.3 },
    tags: ['dairy', 'gluten'],
    vegan: false,
    lowCarb: false,
    noCook: true,
    why: 'Lor ve süzme yoğurttan gelen ~20 g protein, cheesecake tadını hamursuz ve kremasız sağlar.',
  },
  {
    id: 'protein-brownie',
    name: 'Yulaflı protein brownie',
    minutes: 35,
    servings: 6,
    ingredients: [
      { name: 'yulaf unu (öğütülmüş yulaf)', grams: 60, measure: '3/4 su bardağı' },
      { name: 'şekersiz kakao', grams: 25, measure: '3 yemek kaşığı' },
      { name: 'yumurta', grams: 100, measure: '2 adet' },
      { name: 'yumurta akı', grams: 66, measure: '2 yumurta akı' },
      { name: 'yağsız süzme yoğurt', grams: 150, measure: '6 yemek kaşığı' },
      { name: 'muz', grams: 100, measure: '1 orta boy (ezilmiş)' },
      { name: 'kabartma tozu', grams: 4, measure: '1 tatlı kaşığı' },
      { name: 'bitter çikolata (%70–85)', grams: 20, measure: '4 kare (doğranmış)' },
      { name: 'tatlandırıcı (isteğe bağlı)', grams: 0 },
    ],
    steps: [
      'Fırını 175 °C’ye ısıtın, küçük bir kare kalıba pişirme kağıdı serin.',
      'Muzu ezip yumurta, yumurta akı ve süzme yoğurtla çırpın.',
      'Yulaf unu, kakao ve kabartma tozunu ekleyip karıştırın; isterseniz tatlandırıcı ekleyin.',
      'Harcı kalıba döküp doğranmış çikolatayı üzerine serpin.',
      '20–22 dakika pişirin, soğuyunca 6 kareye kesin.',
    ],
    perServing: { kcal: 127, protein: 8.4, carb: 15.8, fat: 4.4 },
    tags: ['egg', 'dairy', 'gluten'],
    vegan: false,
    lowCarb: false,
    noCook: false,
    why: 'Un ve tereyağı yerine yulaf, yumurta ve süzme yoğurt; klasik brownienin yarısından az kaloriyle daha fazla protein.',
  },
  {
    id: 'firin-elma-tarcin',
    name: 'Tarçınlı fırın elma',
    minutes: 35,
    servings: 2,
    ingredients: [
      { name: 'elma', grams: 300, measure: '2 küçük boy' },
      { name: 'ceviz içi', grams: 15, measure: '1,5 yemek kaşığı' },
      { name: 'üzüm pekmezi', grams: 10, measure: '1 tatlı kaşığı' },
      { name: 'tarçın', grams: 1, measure: '1 çay kaşığı' },
      { name: 'su', grams: 50, measure: '1/4 su bardağı' },
    ],
    steps: [
      'Elmaların çekirdek kısmını oyun, dibini delmeyin.',
      'Ceviz, pekmez ve tarçını karıştırıp elmaların içine doldurun.',
      'Fırın kabına dizip dibine suyu ekleyin.',
      '180 °C fırında 25–30 dakika, elmalar yumuşayana kadar pişirin; ılık servis edin.',
    ],
    perServing: { kcal: 143, protein: 1.6, carb: 25.9, fat: 5.2 },
    tags: ['nuts'],
    vegan: true,
    lowCarb: false,
    noCook: false,
    why: 'Bütün elmanın lifi ve tarçının aroması eklenmiş şeker olmadan tatlı his verir.',
  },
  {
    id: 'muz-dondurmasi',
    name: 'Tahinli muz dondurması',
    minutes: 5,
    servings: 2,
    ingredients: [
      { name: 'dondurulmuş muz', grams: 240, measure: '2 orta boy (dilimlenip dondurulmuş)' },
      { name: 'tahin', grams: 10, measure: '1 tatlı kaşığı' },
      { name: 'şekersiz soya sütü', grams: 40, measure: '1/4 su bardağı' },
      { name: 'vanilin', grams: 0, measure: '1 tutam' },
    ],
    steps: [
      'Muzları dilimleyip en az 4 saat dondurun.',
      'Donmuş muzları tahin, soya sütü ve vanilinle birlikte mutfak robotuna alın.',
      'Ara ara kenarları sıyırarak dondurma kıvamına gelene kadar çekin.',
      'Hemen yumuşak servis edin ya da 30 dakika dondurucuda sertleştirin.',
    ],
    perServing: { kcal: 143, protein: 2.8, carb: 28.7, fat: 3.4 },
    tags: [],
    vegan: true,
    lowCarb: false,
    noCook: true,
    why: 'Tamamen muzun doğal şekeriyle tatlanan, eklenmiş şeker ve krema içermeyen dondurma.',
  },
  {
    id: 'cilekli-yogurt-bark',
    name: 'Çilekli yoğurt bark',
    minutes: 10,
    servings: 4,
    ingredients: [
      { name: 'yağsız süzme yoğurt', grams: 300, measure: '1,5 su bardağı' },
      { name: 'bal', grams: 15, measure: '1 yemek kaşığı' },
      { name: 'vanilin', grams: 0, measure: '1 tutam' },
      { name: 'çilek', grams: 150, measure: '8–10 adet' },
      { name: 'bitter çikolata (%70–85)', grams: 20, measure: '4 kare (eritilmiş)' },
    ],
    steps: [
      'Süzme yoğurdu bal ve vanilinle karıştırın.',
      'Pişirme kağıdı serili tepsiye yaklaşık 1 cm kalınlıkta yayın.',
      'Üzerine dilimlenmiş çilekleri bastırın, eritilmiş bitter çikolatayı ince ince gezdirin.',
      'En az 3 saat dondurup 4 eşit parçaya kırın; dondurucuda saklayın.',
    ],
    perServing: { kcal: 98, protein: 8.3, carb: 11.0, fat: 2.5 },
    tags: ['dairy'],
    vegan: false,
    lowCarb: false,
    noCook: true,
    why: 'Parçalara bölünmüş, donuk ve yavaş yenen bir tatlı; porsiyon başı ~8 g protein.',
  },
  {
    id: 'meyveli-chia-puding',
    name: 'Yaban mersinli chia puding',
    minutes: 5,
    servings: 1,
    ingredients: [
      { name: 'chia tohumu', grams: 25, measure: '2 yemek kaşığı' },
      { name: 'şekersiz soya sütü', grams: 200, measure: '1 su bardağı' },
      { name: 'tarçın', grams: 1, measure: '1 tutam' },
      { name: 'yaban mersini (taze/donuk)', grams: 60, measure: '1/2 çay bardağı' },
    ],
    steps: [
      'Chia tohumunu soya sütü ve tarçınla bir kavanozda karıştırın.',
      '5 dakika sonra tekrar karıştırın ki topaklanmasın.',
      'Buzdolabında en az 2 saat (ya da bir gece) bekletin.',
      'Üzerine yaban mersini ekleyip servis edin.',
    ],
    perServing: { kcal: 224, protein: 11.2, carb: 22.4, fat: 11.5 },
    tags: [],
    vegan: true,
    lowCarb: false,
    noCook: true,
    why: 'Chia yaklaşık 9 g lif sağlar; soya sütüyle birlikte bitkisel protein de içerir.',
  },
  {
    id: 'yulafli-muzlu-kurabiye',
    name: 'Yulaflı muzlu kurabiye',
    minutes: 25,
    servings: 6,
    ingredients: [
      { name: 'muz', grams: 240, measure: '2 olgun muz' },
      { name: 'yulaf ezmesi', grams: 120, measure: '1,5 su bardağı' },
      { name: 'kuru üzüm', grams: 30, measure: '2 yemek kaşığı' },
      { name: 'tarçın', grams: 2, measure: '1 tatlı kaşığı' },
    ],
    steps: [
      'Fırını 180 °C’ye ısıtın.',
      'Muzları çatalla iyice ezip yulaf, kuru üzüm ve tarçınla karıştırın.',
      'Kaşıkla 12 küçük top alıp pişirme kağıdı serili tepsiye bastırarak dizin.',
      '15–18 dakika kenarları kızarana kadar pişirin. Porsiyon 2 kurabiyedir.',
    ],
    perServing: { kcal: 127, protein: 3.2, carb: 26.9, fat: 1.4 },
    tags: ['gluten'],
    vegan: true,
    lowCarb: false,
    noCook: false,
    why: 'Şeker ve yağ eklenmeden yalnızca muz ile tatlanır; yulaf lifi kan şekerini daha dengeli yükseltir.',
  },
  {
    id: 'elmali-yulaf-muffin',
    name: 'Elmalı yulaf muffin',
    minutes: 35,
    servings: 8,
    ingredients: [
      { name: 'yulaf unu (öğütülmüş yulaf)', grams: 120, measure: '1,5 su bardağı' },
      { name: 'elma', grams: 200, measure: '2 küçük (rendelenmiş)' },
      { name: 'yumurta', grams: 100, measure: '2 adet' },
      { name: 'yağsız süzme yoğurt', grams: 120, measure: '5 yemek kaşığı' },
      { name: 'bal', grams: 30, measure: '2 yemek kaşığı' },
      { name: 'kabartma tozu', grams: 8, measure: '2 tatlı kaşığı' },
      { name: 'tarçın', grams: 3, measure: '1 tatlı kaşığı' },
      { name: 'ceviz içi', grams: 25, measure: '2,5 yemek kaşığı' },
    ],
    steps: [
      'Fırını 180 °C’ye ısıtın, muffin kalıbına 8 kağıt kap yerleştirin.',
      'Yumurta, süzme yoğurt ve balı çırpın; rendelenmiş elmayı ekleyin.',
      'Yulaf unu, kabartma tozu ve tarçını ekleyip yalnızca birleşene kadar karıştırın.',
      'Kalıplara paylaştırıp üzerine doğranmış ceviz serpin.',
      '20–22 dakika pişirin; kürdan temiz çıkınca hazırdır.',
    ],
    perServing: { kcal: 130, protein: 5.7, carb: 18.3, fat: 4.3 },
    tags: ['egg', 'dairy', 'gluten', 'nuts'],
    vegan: false,
    lowCarb: false,
    noCook: false,
    why: 'Hazır muffinlerin yarısından az kaloriyle; elma ve yulaftan lif, yumurtadan protein.',
  },
  {
    id: 'hurma-ceviz-toplari',
    name: 'Hurma-ceviz enerji topları',
    minutes: 15,
    servings: 6,
    ingredients: [
      { name: 'hurma (çekirdeksiz)', grams: 120, measure: '6 iri hurma' },
      { name: 'ceviz içi', grams: 60, measure: '1/2 su bardağı' },
      { name: 'hindistan cevizi rendesi', grams: 10, measure: '1 yemek kaşığı (bulamak için)' },
    ],
    steps: [
      'Hurmaların çekirdeklerini çıkarın; çok kuruysa 10 dakika ılık suda bekletin.',
      'Hurma ve cevizi mutfak robotunda yapışkan bir hamur olana kadar çekin.',
      'Islak elle 12 küçük top yapın, hindistan cevizine bulayın.',
      'Buzdolabında saklayın. Porsiyon 2 toptur.',
    ],
    perServing: { kcal: 132, protein: 2.0, carb: 16.8, fat: 7.6 },
    tags: ['nuts'],
    vegan: true,
    lowCarb: false,
    noCook: true,
    why: 'Şeker eklenmeden hurmayla tatlanır; ceviz ve lif sayesinde 2 küçük top yeterince doyurur.',
  },
  {
    id: 'bitter-cikolata-findik',
    name: 'Bitter çikolata ve fındık tabağı',
    minutes: 1,
    servings: 1,
    ingredients: [
      { name: 'bitter çikolata (%70–85)', grams: 15, measure: '3 kare (%85 tercih edin)' },
      { name: 'fındık', grams: 10, measure: '7–8 adet' },
    ],
    steps: [
      'Bitter çikolatayı küçük bir tabağa ayırın, paketi kaldırın.',
      'Yanına fındıkları ekleyin.',
      'Her kareyi ağzınızda eritircesine yavaş yiyin. Vegan için süt içermeyen çikolata seçin.',
    ],
    perServing: { kcal: 152, protein: 2.7, carb: 8.6, fat: 12.5 },
    tags: ['nuts'],
    vegan: true,
    lowCarb: true,
    noCook: true,
    why: 'Önceden ayrılmış küçük porsiyon aşırıya kaçmayı önler; yağ ve lif içeriği kan şekerini ani yükseltmez.',
  },
  {
    id: 'fistik-ezmeli-kakaolu-yogurt',
    name: 'Fıstık ezmeli kakaolu yoğurt',
    minutes: 3,
    servings: 1,
    ingredients: [
      { name: 'yağsız süzme yoğurt', grams: 150, measure: '6 yemek kaşığı' },
      { name: 'şekersiz fıstık ezmesi', grams: 10, measure: '2 tatlı kaşığı' },
      { name: 'şekersiz kakao', grams: 4, measure: '2 tatlı kaşığı' },
      { name: 'tatlandırıcı (isteğe bağlı)', grams: 0 },
    ],
    steps: [
      'Süzme yoğurt ile kakaoyu pürüzsüz olana kadar çırpın.',
      'İsterseniz tatlandırıcı ekleyin.',
      'Fıstık ezmesini üzerine kaşıkla girdap şeklinde gezdirip servis edin.',
    ],
    perServing: { kcal: 156, protein: 18.6, carb: 9.7, fat: 6.2 },
    tags: ['dairy', 'nuts'],
    vegan: false,
    lowCarb: true,
    noCook: true,
    why: 'Yaklaşık 18 g protein ve düşük karbonhidratla "Snickers" tadı arayanlar için.',
  },
  {
    id: 'chia-hindistan-cevizi-puding',
    name: 'Hindistan cevizli chia puding',
    minutes: 5,
    servings: 1,
    ingredients: [
      { name: 'chia tohumu', grams: 15, measure: '1,5 yemek kaşığı' },
      { name: 'hindistan cevizi sütü (konserve)', grams: 40, measure: '3 yemek kaşığı' },
      { name: 'şekersiz badem sütü', grams: 140, measure: '3/4 su bardağı' },
      { name: 'hindistan cevizi rendesi', grams: 5, measure: '1 tatlı kaşığı' },
      { name: 'tatlandırıcı (isteğe bağlı)', grams: 0 },
    ],
    steps: [
      'Chia, hindistan cevizi sütü, badem sütü ve isteğe bağlı tatlandırıcıyı karıştırın.',
      '5 dakika sonra tekrar karıştırıp buzdolabında en az 2 saat bekletin.',
      'Üzerine hindistan cevizi rendesi serpip servis edin.',
    ],
    perServing: { kcal: 206, protein: 4.5, carb: 9.5, fat: 18.0 },
    tags: ['nuts'],
    vegan: true,
    lowCarb: true,
    noCook: true,
    why: 'Çok düşük karbonhidratlı, lif ve yağ ağırlıklı bir tatlı; kan şekerini neredeyse hiç yükseltmez.',
  },
  {
    id: 'yogurtlu-panna-cotta',
    name: 'Süzme yoğurtlu panna cotta',
    minutes: 15,
    servings: 2,
    ingredients: [
      { name: 'yağsız süt', grams: 150, measure: '3/4 su bardağı' },
      { name: 'toz jelatin (şekersiz)', grams: 8, measure: '2 tatlı kaşığı' },
      { name: 'yağsız süzme yoğurt', grams: 200, measure: '1 su bardağı' },
      { name: 'vanilin', grams: 0, measure: '1 tutam' },
      { name: 'tatlandırıcı (isteğe bağlı)', grams: 0 },
      { name: 'çilek', grams: 60, measure: '4 adet' },
    ],
    steps: [
      'Jelatini soğuk sütün üzerine serpip 5 dakika şişmeye bırakın.',
      'Sütü kısık ateşte, kaynatmadan jelatin eriyene kadar ısıtın.',
      'Ilıyınca süzme yoğurt, vanilin ve tatlandırıcıyla çırpın.',
      'İki kaseye paylaştırıp en az 3 saat buzdolabında soğutun; ezilmiş çilekle servis edin.',
    ],
    perServing: { kcal: 108, protein: 16.4, carb: 9.7, fat: 0.6 },
    tags: ['dairy'],
    vegan: false,
    lowCarb: true,
    noCook: false,
    why: 'Krema yerine süzme yoğurtla ~16 g protein, 10 g altında karbonhidrat.',
  },
  {
    id: 'tarcinli-lor-ceviz-kase',
    name: 'Tarçınlı lor-ceviz kase',
    minutes: 3,
    servings: 1,
    ingredients: [
      { name: 'lor peyniri', grams: 120, measure: '5 yemek kaşığı' },
      { name: 'ceviz içi', grams: 10, measure: '1 yemek kaşığı' },
      { name: 'tarçın', grams: 1, measure: '1/2 çay kaşığı' },
      { name: 'vanilin', grams: 0, measure: '1 tutam' },
      { name: 'tatlandırıcı (isteğe bağlı)', grams: 0 },
    ],
    steps: [
      'Loru çatalla ezip vanilin ve isteğe bağlı tatlandırıcıyla krema kıvamına getirin.',
      'Üzerine tarçın serpin.',
      'Dövülmüş cevizle tamamlayıp servis edin.',
    ],
    perServing: { kcal: 154, protein: 16.4, carb: 5.4, fat: 7.7 },
    tags: ['dairy', 'nuts'],
    vegan: false,
    lowCarb: true,
    noCook: true,
    why: 'Yaklaşık 16 g protein ve düşük karbonhidrat; tarçın ile şekersiz tatlı aroması.',
  },
  {
    id: 'kakaolu-tofu-mus',
    name: 'Kakaolu tofu mus',
    minutes: 10,
    servings: 4,
    ingredients: [
      { name: 'ipeksi tofu', grams: 300, measure: '1 paket' },
      { name: 'şekersiz kakao', grams: 20, measure: '2,5 yemek kaşığı' },
      { name: 'keçiboynuzu pekmezi', grams: 30, measure: '1,5 yemek kaşığı' },
      { name: 'bitter çikolata (%70–85)', grams: 30, measure: '6 kare (eritilmiş)' },
      { name: 'vanilin', grams: 0, measure: '1 tutam' },
    ],
    steps: [
      'Bitter çikolatayı benmari usulü eritin.',
      'Tofu, kakao, pekmez ve vanilini blenderda pürüzsüz olana kadar çekin.',
      'Eritilmiş çikolatayı ekleyip tekrar çekin.',
      '4 küçük kaseye paylaştırıp en az 1 saat buzdolabında soğutun.',
    ],
    perServing: { kcal: 124, protein: 6.7, carb: 13.7, fat: 5.9 },
    tags: [],
    vegan: true,
    lowCarb: false,
    noCook: false,
    why: 'Krema ve yumurta olmadan, bitkisel protein içeren yoğun çikolatalı mus.',
  },
  {
    id: 'light-kayisi-tatlisi',
    name: 'Süzme yoğurtlu kayısı tatlısı',
    minutes: 25,
    servings: 2,
    ingredients: [
      { name: 'kuru kayısı', grams: 60, measure: '8 adet' },
      { name: 'su', grams: 300, measure: '1,5 su bardağı' },
      { name: 'limon kabuğu rendesi', grams: 0, measure: 'birkaç damla limon suyu' },
      { name: 'yağsız süzme yoğurt', grams: 60, measure: '2,5 yemek kaşığı' },
      { name: 'antep fıstığı (iç, toz)', grams: 8, measure: '1 yemek kaşığı (toz)' },
    ],
    steps: [
      'Kuru kayısıları suyla tencereye alıp 15 dakika yumuşayana kadar haşlayın; şeker eklemeyin.',
      'Limon suyunu ekleyip kendi şurubunda soğumaya bırakın.',
      'Kayısıları yandan açıp içlerine kaymak yerine süzme yoğurt doldurun.',
      'Üzerine toz antep fıstığı serpip porsiyon başı 4 adet servis edin.',
    ],
    perServing: { kcal: 112, protein: 4.9, carb: 20.9, fat: 2.1 },
    tags: ['dairy', 'nuts'],
    vegan: false,
    lowCarb: false,
    noCook: false,
    why: 'Şerbetsiz, kaymaksız klasik; kayısının lifi ve yoğurdun proteiniyle tatlı his.',
  },
]
